# 搜索引擎配置文件

[[engines]]
name = "Bing"
key = "bing"
icon = "brand-bing"
url = "https://www.bing.com/search?&q=%s"
suggest_url = "https://www.bing.com/osjson.aspx?query=%s&language=zh-CN"

[[engines]]
name = "Google"
key = "google"
icon = "brand-google"
url = "https://www.google.com/search?q=%s&sourceid=chrome&ie=UTF-8"
suggest_url = "https://www.google.com/complete/search?client=chrome&q=%s"

[[engines]]
name = "Bilibili"
key = "bilibili"
icon = "brand-bilibili"
url = "https://search.bilibili.com/all?vt=68930313&keyword=%s&search_source=1"
suggest_url = "https://s.search.bilibili.com/main/suggest?func=suggest&suggest_type=accurate&sub_type=tag&main_ver=v1&term=%s"

[[engines]]
name = "Github"
key = "github"
icon = "brand-github"
url = "https://github.com/search?q=%s&type=repositories"
suggest_url = ""

[[engines]]
name = "Yandex"
key = "yandex"
icon = "brand-yandex"
url = "https://yandex.com/search/?text=%s"
suggest_url = "https://suggest.yandex.ru/suggest-ff.cgi?part=%s"
